"""add user gender and address fields

Revision ID: 1561f40c8737
Revises: 031da5dc9bd9
Create Date: 2026-04-15 12:42:30.985499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1561f40c8737'
down_revision: Union[str, Sequence[str], None] = '031da5dc9bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_addresses', sa.Column('address_type', sa.String(length=20), nullable=True))
    op.add_column('shipping_addresses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('shipping_addresses', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('shipping_addresses', 'longitude')
    op.drop_column('shipping_addresses', 'latitude')
    op.drop_column('shipping_addresses', 'address_type')
    # ### end Alembic commands ###
