"""Auth module updates

Revision ID: d5a05a58adcb
Revises: c8106ce458b3
Create Date: 2026-04-15 00:22:18.754161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a05a58adcb'
down_revision: Union[str, Sequence[str], None] = 'c8106ce458b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cart_user_id', 'cart_items', ['user_id'], unique=False)
    op.add_column('orders', sa.Column('order_number', sa.String(length=50), nullable=False))
    op.create_index('ix_order_user_id', 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index('ix_product_category_active', 'products', ['category_id', 'is_active'], unique=False)
    op.create_index('ix_product_name_search', 'products', ['name'], unique=False, postgresql_ops={'name': 'varchar_pattern_ops'})
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'hashed_password')
    op.drop_index('ix_product_name_search', table_name='products', postgresql_ops={'name': 'varchar_pattern_ops'})
    op.drop_index('ix_product_category_active', table_name='products')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index('ix_order_user_id', table_name='orders')
    op.drop_column('orders', 'order_number')
    op.drop_index('ix_cart_user_id', table_name='cart_items')
    # ### end Alembic commands ###
